apiVersion: v1
kind: Service
metadata: 
  name: demo-service
spec:
  ports:
  - port: 3000
    nodePort: 31001
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: demo
  type: NodePort
