apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: helloworld-daemonset
  labels:
    app: helloworld-daemonset
spec:
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: abhigupta1207/helloworld-nodejs
        ports:
        - name: node-port
          containerPort: 3000
