apiVersion: v1
kind: Pod
metadata: 
  name: demo-pod
  labels:
    app: demo
spec:
  containers:
  - name: k8s-demo
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 30
